<template>
	<div class="stats-bar row">

      <span><strong>Ave Games: </strong></span>       
      <span><strong>Ave Height: </strong></span>
      <span><strong>Ave Disp Eff: </strong></span>
      <span><strong>Ave Tackles: </strong></span>
      <span><strong>Ave 1%'s: </strong></span>      

	</div>
</template>
<script>
	
</script>
<style lang="scss">
  @import '../assets/scss/main.scss';

  .stats-bar {
  	// width: 100%;
  	padding-top: 47px;
  	background: $base;
  	min-height: 50px;
    display: flex;
    justify-content: space-around;    

  }





</style>